// Generated by make_archive_context.py - do not edit.
window.ARCHIVE_CONTEXT = {
  "collector": "http://100.84.128.23:8100",
  "queried_at": "2026-09-14T09:56:33+00:00",
  "runs_total": 284,
  "device_labels": 33,
  "runs_sampled": 284,
  "sites": [
    "BGDP03-017",
    "BGPD03-017",
    "BGPD03-019",
    "BPGD03-014",
    "BPGD03-015",
    "BPGD03-016",
    "BPGD03-017",
    "BPGD03-018",
    "BPGD03-018SN:6010675863;6010675863",
    "BPGD03-019",
    "BPGD03-020",
    "BPGD03-021",
    "BPGD03-022",
    "BPGD03-023",
    "BPGF03-018",
    "afbp-palmachim-1",
    "afbp-palmachim-2",
    "afbp-palmachim-3",
    "afbp-palmachim-4",
    "afbp-palmachim-5",
    "avis-test",
    "cuas-13",
    "cuas-14",
    "kela-cuas-15",
    "kela-cuas-16",
    "kela-cuas-17",
    "kela-cuas-18",
    "kela-cuas-19",
    "kela-cuas-20",
    "kela-fob-09-new",
    "kela-fob-11",
    "kela-fob-22",
    "kela-fob-23",
    "kela-fob-24",
    "kela-fob-25",
    "kela-fob-26",
    "kela-fob-backup",
    "kela-gotcha-01",
    "kela-gotcha-02",
    "kela-tlv-dev-03",
    "magen-01",
    "ogmar-8--radar4",
    "ogmar-80-radar-1",
    "ogmar-80-radar2",
    "ogmar-80-radar3",
    "ramda-lidar-pilot",
    "ramda-lidar-pilot-01",
    "ramda-lidar-pilot-02"
  ],
  "by_tool": {
    "magos-apu": {
      "kind": "apu",
      "models": {
        "(vendor unresolved)": [
          "unknown"
        ],
        "Nvidia": [
          "AR Processing Unit (APU)"
        ]
      },
      "vendors": {
        "Nvidia": 21
      },
      "firmwares": [
        "3.1.2-rc5"
      ],
      "runs_without_mac": 2
    },
    "magos-radar": {
      "kind": "radar",
      "models": {
        "(vendor unresolved)": [
          "unknown"
        ],
        "Magosys Systems": [
          "AR-300",
          "SR1000-F",
          "SR500-F"
        ]
      },
      "vendors": {
        "Magosys Systems": 44
      },
      "firmwares": [],
      "runs_without_mac": 5
    },
    "otd": {
      "kind": "modem",
      "models": {
        "Teltonika Networks UAB": [
          "OTD500",
          "OTD50010XXXX"
        ]
      },
      "vendors": {
        "Teltonika Networks UAB": 55
      },
      "firmwares": [
        "OTD5_R_00.07.15.4",
        "OTD5_R_00.07.18.3",
        "OTD5_R_00.07.20.3",
        "OTD5_R_00.07.22.3"
      ],
      "runs_without_mac": 0
    },
    "raythink": {
      "kind": "camera",
      "models": {
        "HangZhou JuRu Technology": [
          "PC464A1",
          "Raythink"
        ],
        "RayThink Technology": [
          "Raythink",
          "XX-MVP-PC4-V100"
        ]
      },
      "vendors": {
        "HangZhou JuRu Technology": 31,
        "RayThink Technology": 15
      },
      "firmwares": [
        "1.000.0000.0.T",
        "B1.0.22.29.16, 2026-09-03",
        "B1.2.01.01.15, 2026-05-14"
      ],
      "runs_without_mac": 0
    },
    "rutm": {
      "kind": "router",
      "models": {
        "Teltonika Networks UAB": [
          "RUTM08",
          "RUTM0800XXXX"
        ]
      },
      "vendors": {
        "Teltonika Networks UAB": 52
      },
      "firmwares": [
        "RUTM_R_00.07.19.4",
        "RUTM_R_00.07.22.1",
        "RUTM_R_00.07.22.3"
      ],
      "runs_without_mac": 0
    },
    "speaker": {
      "kind": "speaker",
      "models": {
        "Provision-ISR": [
          "Provision-ISR speaker"
        ]
      },
      "vendors": {
        "Provision-ISR": 25
      },
      "firmwares": [
        "V3.3.39-PR1"
      ],
      "runs_without_mac": 0
    },
    "tsw": {
      "kind": "switch",
      "models": {
        "Teltonika Networks UAB": [
          "TSW202",
          "TSW20200XXXX"
        ]
      },
      "vendors": {
        "Teltonika Networks UAB": 34
      },
      "firmwares": [
        "TSW2_R_00.01.07.1"
      ],
      "runs_without_mac": 0
    }
  }
};
