// Generated by sitemap.py export - do not edit.
// Regenerate with: sitemap.py export sites/*.yaml -o site-data.js
window.SITE_DATA = {
  "version": 1,
  "sites": [
    {
      "name": "kela-fob-03",
      "status": "provisional",
      "subnet": "192.168.88.0/24",
      "uplink": "router",
      "source_path": "sites/kela-fob-03.yaml",
      "nodes": {
        "router": {
          "name": "router",
          "kind": "router",
          "vendor": "Teltonika Networks",
          "model": "RUTM08",
          "firmware": "RUTM_R_00.07.24.3",
          "candidates": [],
          "candidate_basis": null,
          "mac": "20:97:27:36:55:ec",
          "evidence": {
            "*": "arp",
            "model": "device-api",
            "firmware": "device-api",
            "addr": "device-api"
          },
          "proven": {
            "vendor": true,
            "model": true,
            "firmware": true,
            "addr": true,
            "present": true
          },
          "verified_at": "2026-09-14",
          "addr": "192.168.88.1",
          "addr_source": "static-manual",
          "interfaces": [
            {
              "name": "br-lan",
              "addr": "192.168.88.1",
              "scope": "internal",
              "prefix": 24,
              "note": null
            },
            {
              "name": "tailscale0",
              "addr": "100.64.242.104",
              "scope": "external",
              "prefix": 32,
              "note": "the tailnet address, and how this survey reached the site"
            },
            {
              "name": "wan",
              "addr": "192.168.1.164",
              "scope": "external",
              "prefix": 24,
              "note": "uplink to another Teltonika at 192.168.1.1"
            }
          ],
          "interfaces_read": true,
          "roles": [
            "dhcp-server",
            "dns-resolver",
            "default-gateway"
          ],
          "critical": true,
          "notes": "Read off the device 2026-09-14 over SSH and REST. `ubus call system board` reports model \"Teltonika RUTM08\" outright, which settles what the OUI could not — Teltonika makes the OTD500 and TSW202 on this same 20:97:27 prefix. The inferred shortlist (RUTM08, from it being the only RUT-M model in 52 archived rutm runs) was RIGHT this time. Worth recording precisely because the radar and camera shortlists were both wrong: a shortlist is a lead, and a lead can be correct — which is why \"~\" has to stay visually distinct from \"✓\" in either direction.\nSerial 6008952997, hardware version 0004, batch 0037, bootloader 2.23.3. Self-reported LAN MAC 2097273655EC matches the ARP observation at .1 exactly; the WAN port is one higher at ...:ED. Running OpenWrt 21.02.0 (r16279-5cc0535800) on kernel 6.6.126, MediaTek MT7621. The hwinfo block reports mobile=false and dual_sim=false, consistent with the RUTM08 being the non-cellular RUT-M — so this site's path to the carrier is NOT through this device's own modem.\nFirmware RUTM_R_00.07.24.3 is already the version avis/tec-861-teltonika-firmware-upgrade-path-to-07243-security-across is written to roll out, so this unit needs nothing from that work.\nWhat IS now settled is what this device DOES, read 2026-09-14 from the DHCP leases held on two independent hosts (the server at .10 and the operator station at .29). Both leases name SERVER_ADDRESS=192.168.88.1, ROUTER=192.168.88.1 and DNS=192.168.88.1, and `networkctl` on .29 reports \"Address: 192.168.88.29 (DHCP4 via 192.168.88.1)\". So this device is the subnet's DHCP server, its default gateway and its DNS resolver. That is two separate clients agreeing, not an inference from the .1 address.\n`addr_source` is therefore static-manual rather than static-bench: a DHCP server does not lease its own address, so .1 is configured on the device — but nothing shows the bench configured it, and static-bench would claim that.",
          "addr_pool": null,
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": "Teltonika RUTM08",
          "net_parents": [],
          "net_children": [
            {
              "node": "teltonika_118",
              "port": "lan3",
              "peer_port": null,
              "media": "ethernet",
              "notes": "The router's bridge FDB learns EVERY site MAC on lan3, and lan1/lan2 have no carrier, so one cable leaves the router and the rest of the site is behind the .118 switch. This edge is the part that is proven. The port on the .118 end is unknown — `peer_port` is deliberately absent rather than guessed — and so is every device-to-switch-port pairing, because the router cannot see past its own port. The TSW202's own MAC table is what completes this, and that needs its credential."
            }
          ],
          "power_in": [],
          "power_out": []
        },
        "operator_station": {
          "name": "operator_station",
          "kind": "operator-station",
          "vendor": "Dell Inc.",
          "model": "Dell Pro Micro QCM1250",
          "firmware": "1.4.4",
          "candidates": [],
          "candidate_basis": null,
          "mac": "e8:cf:83:3f:f3:83",
          "evidence": {
            "*": "arp",
            "vendor": "device-api",
            "model": "device-api",
            "firmware": "device-api"
          },
          "proven": {
            "vendor": true,
            "model": true,
            "firmware": true,
            "addr": true,
            "present": true
          },
          "verified_at": "2026-09-14",
          "addr": "192.168.88.29",
          "addr_source": "dhcp-lease",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.29",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [],
          "critical": false,
          "notes": "Hostname kela-fob-03-operator. Identity read on the host itself 2026-09-14 from /sys/class/dmi/id, which is world-readable and needed no sudo: vendor Dell Inc., model Dell Pro Micro QCM1250, board 04C6CY, chassis type 3 (desktop). `firmware` holds the BIOS version (1.4.4, dated 2025-05-08), the firmware analogue on a PC. product_serial reads empty — that DMI field is root-only here, so the serial is genuinely unread rather than absent. The OS is Ubuntu 22.04.5 LTS on kernel 6.8.0-101-generic; that is software on its own schedule, so it is recorded here rather than in the firmware field. Worth noting for patching: the server at .10 is on 24.04.4, so the two PCs are a release apart.\nThe MAC the host reports for enp128s31f6 is e8:cf:83:3f:f3:83, which matches the router's ARP observation exactly — the cross-check that rules out having read a bench machine over the colliding 192.168.88.0/24.\nReached by forwarding a local port to .29:22 through the site server, so nothing was written to either box. SSH keys do NOT work here and the reason is on the far end: this sshd advertises only password auth (`Authentications that can continue: password`), so a key installed by ssh-copy-id is never offered and never used. Fixing that is an sshd config change, which is a write to production and was not made.\n`addr_source` is dhcp-lease, read off the interface itself: the address carries `scope global dynamic` with a finite valid_lft, and /run/systemd/netif/leases names .1 as the server. Not a static.\nStill no candidates list, and that is correct: operator stations do not go through a bench tool, so bench-central will never hold one.",
          "addr_pool": null,
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": null,
          "net_parents": [],
          "net_children": [],
          "power_in": [],
          "power_out": []
        },
        "camera_1": {
          "name": "camera_1",
          "kind": "camera",
          "vendor": "HangZhou JuRu Technology",
          "model": "SG-PTZ",
          "firmware": "1.000.0000.0.R",
          "candidates": [],
          "candidate_basis": null,
          "mac": "bc:74:d7:81:17:b1",
          "evidence": {
            "*": "arp",
            "model": "device-api",
            "firmware": "device-api"
          },
          "proven": {
            "vendor": true,
            "model": true,
            "firmware": true,
            "addr": true,
            "present": true
          },
          "verified_at": "2026-09-14",
          "addr": "192.168.88.30",
          "addr_source": "static-bench",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.30",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [],
          "critical": false,
          "notes": "Model and firmware read off the camera's own RPC2 API on 2026-09-14 (read-only client armed after login). Serial KC0500PAZ00052, which matches the ARP hostname KC0500PAZ00052.lan exactly, and the camera reported its own MAC as bc:74:d7:81:17:b1 — identical to the ARP observation at .30. Those two independent matches are what rule out having reached a bench camera on the same address.\nThe shortlist was PC464A1 and it was WRONG: every BC:74:D7 camera in the archive reports PC464A1, and this one is an SG-PTZ — a pan/tilt/zoom unit, a different class of device from the fixed PC464A1. So the OUI correlation that produced that shortlist does not hold at this site. The old note about the serial prefix differs from camera_2 (KC vs HF) and nothing maps that prefix to a model, so the two are not necessarily identical units.",
          "addr_pool": "cameras",
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": null,
          "net_parents": [],
          "net_children": [],
          "power_in": [],
          "power_out": []
        },
        "camera_2": {
          "name": "camera_2",
          "kind": "camera",
          "vendor": "HangZhou JuRu Technology",
          "model": "SG-PTZ",
          "firmware": "1.000.0000.0.R",
          "candidates": [],
          "candidate_basis": null,
          "mac": "bc:74:d7:80:c6:4d",
          "evidence": {
            "*": "arp",
            "model": "device-api",
            "firmware": "device-api"
          },
          "proven": {
            "vendor": true,
            "model": true,
            "firmware": true,
            "addr": true,
            "present": true
          },
          "verified_at": "2026-09-14",
          "addr": "192.168.88.31",
          "addr_source": "static-bench",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.31",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [],
          "critical": false,
          "notes": "Read off the device 2026-09-14, same as camera_1. Serial HF0428PAZ00055, matching its ARP hostname; self-reported MAC matched the ARP observation at .31. Same model and firmware as camera_1 despite a different serial prefix (HF0428 vs KC0500) — which settles an open question in this file: the serial prefix does NOT encode the model, so it can never be used to narrow one.",
          "addr_pool": "cameras",
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": null,
          "net_parents": [],
          "net_children": [],
          "power_in": [],
          "power_out": []
        },
        "radar_1": {
          "name": "radar_1",
          "kind": "radar",
          "vendor": "Magosys Systems",
          "model": "SR1000-I",
          "firmware": "1.1.4",
          "candidates": [],
          "candidate_basis": null,
          "mac": "8c:1f:64:e7:4c:46",
          "evidence": {
            "*": "arp",
            "model": "device-api",
            "firmware": "device-api"
          },
          "proven": {
            "vendor": true,
            "model": true,
            "firmware": true,
            "addr": true,
            "present": true
          },
          "verified_at": "2026-09-14",
          "addr": "192.168.88.130",
          "addr_source": "static-bench",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.130",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [],
          "critical": true,
          "notes": "Model and firmware read off the radar's own dashboard API on 2026-09-14 (read-only client, one login) — and the login that worked was admin/password, the Magos FACTORY DEFAULT. See the SECURITY FINDING at the foot of this file; that is a fact about this site, not a detail of the probe. Serial 12510000-082. The radar reported its own MAC as 8c:1f:64:e7:4c:46, identical to the MAC the site server's ARP table observed at .130 — that match is what proves this was THIS site's radar and not a bench unit, since 192.168.88.0/24 is also the bench subnet. Firmware is the System Software version; the unit separately reports Dashboard 2.4.3, DSP 1.2.4 and FPGA 1.2.6, and those move independently. Outside the documented .50-.53 radar plan. Radar rather than APU by the Magosys-vs-NVIDIA OUI split, not by reading the unit.",
          "addr_pool": null,
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": "SR1000-I",
          "net_parents": [],
          "net_children": [],
          "power_in": [],
          "power_out": []
        },
        "radar_2": {
          "name": "radar_2",
          "kind": "radar",
          "vendor": "Magosys Systems",
          "model": "SR1000-I",
          "firmware": "1.1.4",
          "candidates": [],
          "candidate_basis": null,
          "mac": "8c:1f:64:e7:47:d3",
          "evidence": {
            "*": "arp",
            "model": "device-api",
            "firmware": "device-api"
          },
          "proven": {
            "vendor": true,
            "model": true,
            "firmware": true,
            "addr": true,
            "present": true
          },
          "verified_at": "2026-09-14",
          "addr": "192.168.88.131",
          "addr_source": "static-bench",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.131",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [],
          "critical": true,
          "notes": "Read off the device 2026-09-14, same as radar_1 — including the factory-default admin/password login; see the SECURITY FINDING at the foot of this file. Serial 12510000-005. Self-reported MAC matched the ARP observation at .131. Component versions identical to radar_1 (Dashboard 2.4.3, DSP 1.2.4, FPGA 1.2.6).",
          "addr_pool": null,
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": "SR1000-I",
          "net_parents": [],
          "net_children": [],
          "power_in": [],
          "power_out": []
        },
        "radar_3": {
          "name": "radar_3",
          "kind": "radar",
          "vendor": "Magosys Systems",
          "model": null,
          "firmware": null,
          "candidates": [
            "SR1000-I"
          ],
          "candidate_basis": "its two neighbours at .130 and .131 both read as SR1000-I off their own API, and all four share the Magosys OUI and were installed together — so this is the likeliest model, but it was NOT read off this unit",
          "mac": "8c:1f:64:e7:48:c7",
          "evidence": {
            "*": "arp"
          },
          "proven": {
            "vendor": true,
            "model": false,
            "firmware": false,
            "addr": true,
            "present": true
          },
          "verified_at": null,
          "addr": "192.168.88.132",
          "addr_source": "static-bench",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.132",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [],
          "critical": true,
          "notes": "COULD NOT BE IDENTIFIED, and the reason matters. This unit answers ICMP (3/3, 0% loss) and sits in the site server's neighbour table, so it is powered and on the network — but it serves NO TCP port at all. Re-checked 2026-09-14 with a full connect scan of ports 1-10240 run FROM THE SITE SERVER, on the same L2 segment as the radar: zero open ports. The same scan from the same host finds 22, 80 and 443 open on .130 and .131. So this is not a vantage-point artifact and not the 192.168.88.0/24 bench collision producing a false negative — it is the radar.\nThat settles a specific question: a port forward cannot help here. Forwarding needs something listening to forward to, and these two units are not listening on anything. The Magos dashboard API is plain HTTP on 80, so there is nothing to query and no credential would change the outcome.\nWorth an operator's attention on its own merits: two of four radars serving no management port is either a stopped web service, a host firewall or VLAN difference on these two, a management interface bound to an address on another subnet, or a genuinely different product variant. Detections may still be flowing — that rides a separate path — so this is NOT evidence the radar is down. Deciding between those needs the TSW202's per-port view, or physical/console access.\nThe router's view did narrow it. This MAC appears in the router's bridge FDB on lan3 (2026-09-14) exactly like every working device, so the unit is cabled and forwarding frames at layer 2. Cabling and power are therefore NOT the fault: it is up enough to answer ICMP and put frames on the wire, while serving nothing above that. Reads like a stopped service or a host firewall rather than a dead radar or a dead drop.",
          "addr_pool": null,
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": null,
          "net_parents": [],
          "net_children": [],
          "power_in": [],
          "power_out": []
        },
        "radar_4": {
          "name": "radar_4",
          "kind": "radar",
          "vendor": "Magosys Systems",
          "model": null,
          "firmware": null,
          "candidates": [
            "SR1000-I"
          ],
          "candidate_basis": "its two neighbours at .130 and .131 both read as SR1000-I off their own API, and all four share the Magosys OUI and were installed together — so this is the likeliest model, but it was NOT read off this unit",
          "mac": "8c:1f:64:e7:48:d3",
          "evidence": {
            "*": "arp"
          },
          "proven": {
            "vendor": true,
            "model": false,
            "firmware": false,
            "addr": true,
            "present": true
          },
          "verified_at": null,
          "addr": "192.168.88.133",
          "addr_source": "static-bench",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.133",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [],
          "critical": true,
          "notes": "COULD NOT BE IDENTIFIED, and the reason matters. This unit answers ICMP (3/3, 0% loss) and sits in the site server's neighbour table, so it is powered and on the network — but it serves NO TCP port at all. Re-checked 2026-09-14 with a full connect scan of ports 1-10240 run FROM THE SITE SERVER, on the same L2 segment as the radar: zero open ports. The same scan from the same host finds 22, 80 and 443 open on .130 and .131. So this is not a vantage-point artifact and not the 192.168.88.0/24 bench collision producing a false negative — it is the radar.\nThat settles a specific question: a port forward cannot help here. Forwarding needs something listening to forward to, and these two units are not listening on anything. The Magos dashboard API is plain HTTP on 80, so there is nothing to query and no credential would change the outcome.\nWorth an operator's attention on its own merits: two of four radars serving no management port is either a stopped web service, a host firewall or VLAN difference on these two, a management interface bound to an address on another subnet, or a genuinely different product variant. Detections may still be flowing — that rides a separate path — so this is NOT evidence the radar is down. Deciding between those needs the TSW202's per-port view, or physical/console access.\nThe router's view did narrow it. This MAC appears in the router's bridge FDB on lan3 (2026-09-14) exactly like every working device, so the unit is cabled and forwarding frames at layer 2. Cabling and power are therefore NOT the fault: it is up enough to answer ICMP and put frames on the wire, while serving nothing above that. Reads like a stopped service or a host firewall rather than a dead radar or a dead drop.",
          "addr_pool": null,
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": null,
          "net_parents": [],
          "net_children": [],
          "power_in": [],
          "power_out": []
        },
        "server": {
          "name": "server",
          "kind": "server",
          "vendor": "Dell Inc.",
          "model": "Dell Pro Max Tower T2 FCT2250",
          "firmware": "1.6.1",
          "candidates": [],
          "candidate_basis": null,
          "mac": null,
          "evidence": {
            "*": "arp",
            "vendor": "device-api",
            "model": "device-api",
            "firmware": "device-api"
          },
          "proven": {
            "vendor": true,
            "model": true,
            "firmware": true,
            "addr": true,
            "present": true
          },
          "verified_at": "2026-09-14",
          "addr": "192.168.88.10",
          "addr_source": "dhcp-lease",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.10",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [
            "ntp-server"
          ],
          "critical": true,
          "notes": "Hostname kela-fob-03, a Linux host on enp128s31f6 also carrying tailscale0 and a k3s flannel/cni0 bridge. Every bench tool points its NTP at .10, so this is the site's time source as well as its application server. Not a bench-managed device, so bench-central will never hold a model for it. Address confirmed on the host itself (2026-09-14, `ip -4 addr`): 192.168.88.10/24 on enp128s31f6, held as a DHCP lease rather than a static — `scope global dynamic` with a finite valid_lft, and /run/systemd/netif/leases names SERVER_ADDRESS= 192.168.88.1. `addr_source` was corrected from static-bench to dhcp-lease on 2026-09-14 to match. This is worth an operator's attention rather than just a field fix: every bench tool points its NTP at .10, and a site time source on a lease can move. The fix is a static reservation on the router, which is a write and was not made.\nIdentity read on the host itself 2026-09-14 from /sys/class/dmi/id, which is world-readable and needed no sudo and no extra credential — the SSH access already in use was enough. Vendor Dell Inc., model Dell Pro Max Tower T2 FCT2250, board 0D8XDK. `firmware` holds the BIOS version (1.6.1), since that is the firmware analogue on a PC; the OS is Ubuntu 24.04.4 LTS on kernel 6.8.0-139-generic, which is software and moves on its own schedule, so it is recorded here rather than in the firmware field.",
          "addr_pool": null,
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": null,
          "net_parents": [],
          "net_children": [],
          "power_in": [],
          "power_out": []
        },
        "teltonika_118": {
          "name": "teltonika_118",
          "kind": "network-device",
          "vendor": "Teltonika Networks",
          "model": null,
          "firmware": null,
          "candidates": [
            "TSW202"
          ],
          "candidate_basis": "the 209727a0 and 209727ca MAC blocks hold TSW202 units only (9 of 9 across the device-label store), while every OTD500 and RUTM08 sits in the 2097272b-20972749 range; n=1 for the a0 block specifically, so treat this as suggestive rather than settled. A read-only TCP check from the site server on 2026-09-14 found 22, 80 and 443 all open, which is the RutOS profile (SSH plus the HTTPS management UI) and is consistent with a TSW202 — but the router at .1 and any other RutOS device present the same three ports, so this narrows the family, not the model.",
          "mac": "20:97:27:a0:ec:70",
          "evidence": {
            "*": "arp"
          },
          "proven": {
            "vendor": true,
            "model": false,
            "firmware": false,
            "addr": true,
            "present": true
          },
          "verified_at": null,
          "addr": "192.168.88.118",
          "addr_source": "static-bench",
          "interfaces": [
            {
              "name": null,
              "addr": "192.168.88.118",
              "scope": "internal",
              "prefix": null,
              "note": null
            }
          ],
          "interfaces_read": false,
          "roles": [],
          "critical": false,
          "notes": "STILL A SHORTLIST, but only just, and the reason is worth being pedantic about. The router's DHCP lease table (read 2026-09-14) shows this MAC taking .118 with the hostname **TSW202**. That is the device announcing its own name over DHCP — far stronger than the OUI guess it replaces — but a hostname is not the model field. `dhcp-lease` evidence proves present/mac/vendor/addr and deliberately does NOT prove `model`, so this stays \"~\". Reading its model properly needs a login, which is blocked (see below).\nThat same lease is the answer to why the login fails. Every other provisioned device here carries a provisioned hostname (rut-kela-fob-03, kela-fob-03, kela-fob-03-operator); this one still carries the Teltonika factory default, \"TSW202\". So this switch was never run through the bench — which is also why the shared bench password is rejected on both SSH and REST (tried once each, 2026-09-14). It is presumably still on its per-device factory label password.\nAN UNPROVISIONED MANAGED SWITCH IN PRODUCTION is worth an operator's attention on its own: no hostname, no known credential, and nothing about its configuration has ever been verified. It is also the last thing standing between this map and a full cabling answer — a managed switch holds the per-port MAC table, and the router's own table (below) proves every device at this site sits behind it.",
          "addr_pool": null,
          "poe_budget_w": null,
          "poe_managed": false,
          "device_model": null,
          "net_parents": [
            {
              "node": "router",
              "port": "lan3",
              "peer_port": null,
              "media": "ethernet",
              "notes": "The router's bridge FDB learns EVERY site MAC on lan3, and lan1/lan2 have no carrier, so one cable leaves the router and the rest of the site is behind the .118 switch. This edge is the part that is proven. The port on the .118 end is unknown — `peer_port` is deliberately absent rather than guessed — and so is every device-to-switch-port pairing, because the router cannot see past its own port. The TSW202's own MAC table is what completes this, and that needs its credential."
            }
          ],
          "net_children": [],
          "power_in": [],
          "power_out": []
        }
      },
      "net": [
        {
          "parent": "router",
          "child": "teltonika_118",
          "port": "lan3",
          "peer_port": null,
          "media": "ethernet",
          "notes": "The router's bridge FDB learns EVERY site MAC on lan3, and lan1/lan2 have no carrier, so one cable leaves the router and the rest of the site is behind the .118 switch. This edge is the part that is proven. The port on the .118 end is unknown — `peer_port` is deliberately absent rather than guessed — and so is every device-to-switch-port pairing, because the router cannot see past its own port. The TSW202's own MAC table is what completes this, and that needs its credential.",
          "evidence": {
            "by_claim": {
              "*": "switch-table"
            }
          },
          "verified_at": "2026-09-14"
        }
      ],
      "power": [],
      "reservations": [
        {
          "name": "infra",
          "start": "192.168.88.1",
          "end": "192.168.88.3",
          "owner": "bench",
          "dynamic": false,
          "label": "192.168.88.1-192.168.88.3"
        },
        {
          "name": "cameras",
          "start": "192.168.88.30",
          "end": "192.168.88.50",
          "owner": "bench",
          "dynamic": true,
          "label": "192.168.88.30-192.168.88.50"
        }
      ],
      "tree": [
        {
          "depth": 0,
          "node": "router",
          "port": null,
          "peer_port": null
        },
        {
          "depth": 1,
          "node": "teltonika_118",
          "port": "lan3",
          "peer_port": null
        }
      ],
      "topology": {
        "boxes": [
          {
            "name": "__internet__",
            "label": "internet",
            "layer": 0,
            "kind": "internet",
            "real": false,
            "note": "over the router's SIM. Nothing here has read the WAN side."
          },
          {
            "name": "router",
            "label": "router",
            "layer": 1,
            "kind": "router",
            "real": true,
            "note": "router is recorded as default-gateway, with evidence"
          },
          {
            "name": "teltonika_118",
            "label": "teltonika 118",
            "layer": 2,
            "kind": "network-device",
            "real": true,
            "note": "shortlisted as TSW202, which is a switch - a shortlist is a lead and not a reading"
          },
          {
            "name": "camera_1",
            "label": "camera 1",
            "layer": 3,
            "kind": "camera",
            "real": true,
            "note": null
          },
          {
            "name": "camera_2",
            "label": "camera 2",
            "layer": 3,
            "kind": "camera",
            "real": true,
            "note": null
          },
          {
            "name": "operator_station",
            "label": "operator station",
            "layer": 3,
            "kind": "operator-station",
            "real": true,
            "note": null
          },
          {
            "name": "radar_1",
            "label": "radar 1",
            "layer": 3,
            "kind": "radar",
            "real": true,
            "note": null
          },
          {
            "name": "radar_2",
            "label": "radar 2",
            "layer": 3,
            "kind": "radar",
            "real": true,
            "note": null
          },
          {
            "name": "radar_3",
            "label": "radar 3",
            "layer": 3,
            "kind": "radar",
            "real": true,
            "note": null
          },
          {
            "name": "radar_4",
            "label": "radar 4",
            "layer": 3,
            "kind": "radar",
            "real": true,
            "note": null
          },
          {
            "name": "server",
            "label": "server",
            "layer": 3,
            "kind": "server",
            "real": true,
            "note": null
          }
        ],
        "edges": [
          {
            "parent": "router",
            "child": "teltonika_118",
            "source": "declared",
            "basis": "The router's bridge FDB learns EVERY site MAC on lan3, and lan1/lan2 have no carrier, so one cable leaves the router and the rest of the site is behind the .118 switch. This edge is the part that is proven. The port on the .118 end is unknown — `peer_port` is deliberately absent rather than guessed — and so is every device-to-switch-port pairing, because the router cannot see past its own port. The TSW202's own MAC table is what completes this, and that needs its credential.",
            "port": "lan3",
            "peer_port": null,
            "evidence": "switch-table"
          },
          {
            "parent": "__internet__",
            "child": "router",
            "source": "pattern",
            "basis": "the FOB's internet leg is the router's SIM, mounted high for signal. Not read from the device.",
            "port": null,
            "peer_port": null,
            "evidence": null
          },
          {
            "parent": "teltonika_118",
            "child": "camera_1",
            "source": "pattern",
            "basis": "everything on the LAN hangs off teltonika_118; which port needs its MAC-address table",
            "port": null,
            "peer_port": null,
            "evidence": null
          },
          {
            "parent": "teltonika_118",
            "child": "camera_2",
            "source": "pattern",
            "basis": "everything on the LAN hangs off teltonika_118; which port needs its MAC-address table",
            "port": null,
            "peer_port": null,
            "evidence": null
          },
          {
            "parent": "teltonika_118",
            "child": "operator_station",
            "source": "pattern",
            "basis": "everything on the LAN hangs off teltonika_118; which port needs its MAC-address table",
            "port": null,
            "peer_port": null,
            "evidence": null
          },
          {
            "parent": "teltonika_118",
            "child": "radar_1",
            "source": "pattern",
            "basis": "everything on the LAN hangs off teltonika_118; which port needs its MAC-address table",
            "port": null,
            "peer_port": null,
            "evidence": null
          },
          {
            "parent": "teltonika_118",
            "child": "radar_2",
            "source": "pattern",
            "basis": "everything on the LAN hangs off teltonika_118; which port needs its MAC-address table",
            "port": null,
            "peer_port": null,
            "evidence": null
          },
          {
            "parent": "teltonika_118",
            "child": "radar_3",
            "source": "pattern",
            "basis": "everything on the LAN hangs off teltonika_118; which port needs its MAC-address table",
            "port": null,
            "peer_port": null,
            "evidence": null
          },
          {
            "parent": "teltonika_118",
            "child": "radar_4",
            "source": "pattern",
            "basis": "everything on the LAN hangs off teltonika_118; which port needs its MAC-address table",
            "port": null,
            "peer_port": null,
            "evidence": null
          },
          {
            "parent": "teltonika_118",
            "child": "server",
            "source": "pattern",
            "basis": "everything on the LAN hangs off teltonika_118; which port needs its MAC-address table",
            "port": null,
            "peer_port": null,
            "evidence": null
          }
        ],
        "router": "router",
        "switches": [
          "teltonika_118"
        ],
        "notes": [],
        "counts": {
          "declared": 1,
          "pattern": 9
        }
      },
      "off_tree": [
        "camera_1",
        "camera_2",
        "operator_station",
        "radar_1",
        "radar_2",
        "radar_3",
        "radar_4",
        "server"
      ],
      "poe": {},
      "findings": [
        {
          "severity": "warn",
          "code": "dhcp-pinned-addr",
          "message": "has addr 192.168.88.29 but addr_source is 'dhcp-lease' — record it as a static reservation on the router, or drop the addr",
          "where": "operator_station"
        },
        {
          "severity": "warn",
          "code": "dhcp-pinned-addr",
          "message": "has addr 192.168.88.10 but addr_source is 'dhcp-lease' — record it as a static reservation on the router, or drop the addr",
          "where": "server"
        },
        {
          "severity": "warn",
          "code": "model-narrowed-not-known",
          "message": "could be SR1000-I (its two neighbours at .130 and .131 both read as SR1000-I off their own API, and all four share the Magosys OUI and were installed together — so this is the likeliest model, but it was NOT read off this unit). That is a shortlist, not the model — only the device or a bench record settles it.",
          "where": "radar_3"
        },
        {
          "severity": "warn",
          "code": "model-narrowed-not-known",
          "message": "could be SR1000-I (its two neighbours at .130 and .131 both read as SR1000-I off their own API, and all four share the Magosys OUI and were installed together — so this is the likeliest model, but it was NOT read off this unit). That is a shortlist, not the model — only the device or a bench record settles it.",
          "where": "radar_4"
        },
        {
          "severity": "warn",
          "code": "model-narrowed-not-known",
          "message": "could be TSW202 (the 209727a0 and 209727ca MAC blocks hold TSW202 units only (9 of 9 across the device-label store), while every OTD500 and RUTM08 sits in the 2097272b-20972749 range; n=1 for the a0 block specifically, so treat this as suggestive rather than settled. A read-only TCP check from the site server on 2026-09-14 found 22, 80 and 443 all open, which is the RutOS profile (SSH plus the HTTPS management UI) and is consistent with a TSW202 — but the router at .1 and any other RutOS device present the same three ports, so this narrows the family, not the model.). That is a shortlist, not the model — only the device or a bench record settles it.",
          "where": "teltonika_118"
        },
        {
          "severity": "warn",
          "code": "net-orphan",
          "message": "no data path back to the uplink 'router'",
          "where": "camera_1"
        },
        {
          "severity": "warn",
          "code": "net-orphan",
          "message": "no data path back to the uplink 'router'",
          "where": "camera_2"
        },
        {
          "severity": "warn",
          "code": "net-orphan",
          "message": "no data path back to the uplink 'router'",
          "where": "operator_station"
        },
        {
          "severity": "warn",
          "code": "net-orphan",
          "message": "no data path back to the uplink 'router'",
          "where": "radar_1"
        },
        {
          "severity": "warn",
          "code": "net-orphan",
          "message": "no data path back to the uplink 'router'",
          "where": "radar_2"
        },
        {
          "severity": "warn",
          "code": "net-orphan",
          "message": "no data path back to the uplink 'router'",
          "where": "radar_3"
        },
        {
          "severity": "warn",
          "code": "net-orphan",
          "message": "no data path back to the uplink 'router'",
          "where": "radar_4"
        },
        {
          "severity": "warn",
          "code": "net-orphan",
          "message": "no data path back to the uplink 'router'",
          "where": "server"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "camera_1"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "camera_2"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "operator_station"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "radar_1"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "radar_2"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "radar_3"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "radar_4"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "router"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "server"
        },
        {
          "severity": "warn",
          "code": "unpowered",
          "message": "nothing declared as powering it (site is provisional)",
          "where": "teltonika_118"
        }
      ],
      "coverage": {
        "vendor": {
          "proven": 10,
          "claimed": 10,
          "total": 10,
          "pct": 100.0
        },
        "model": {
          "proven": 7,
          "claimed": 7,
          "total": 10,
          "pct": 70.0
        },
        "firmware": {
          "proven": 7,
          "claimed": 7,
          "total": 10,
          "pct": 70.0
        },
        "addr": {
          "proven": 10,
          "claimed": 10,
          "total": 10,
          "pct": 100.0
        },
        "link": {
          "proven": 1,
          "claimed": 1,
          "total": 1,
          "pct": 100.0
        },
        "power": {
          "proven": 0,
          "claimed": 0,
          "total": 0,
          "pct": null
        },
        "draw": {
          "proven": 0,
          "claimed": 0,
          "total": 0,
          "pct": null
        },
        "by_source": {
          "arp": 10,
          "device-api": 7,
          "switch-table": 1
        },
        "survey_only_feeds": 0
      },
      "counts": {
        "nodes": 10,
        "net": 1,
        "power": 0,
        "errors": 0,
        "warnings": 23
      }
    }
  ],
  "devices": {
    "PLANET IGS-4215-8UP2T2S": {
      "model": "PLANET IGS-4215-8UP2T2S",
      "vendor": "PLANET",
      "kind": "poe-switch",
      "form_factor": "din-rail",
      "ports": [
        {
          "id": "gi1",
          "role": "poe",
          "label": null,
          "row": 0,
          "powers": true
        },
        {
          "id": "gi2",
          "role": "poe",
          "label": null,
          "row": 0,
          "powers": true
        },
        {
          "id": "gi3",
          "role": "poe",
          "label": null,
          "row": 0,
          "powers": true
        },
        {
          "id": "gi4",
          "role": "poe",
          "label": null,
          "row": 0,
          "powers": true
        },
        {
          "id": "gi5",
          "role": "poe",
          "label": null,
          "row": 0,
          "powers": true
        },
        {
          "id": "gi6",
          "role": "poe",
          "label": null,
          "row": 0,
          "powers": true
        },
        {
          "id": "gi7",
          "role": "poe",
          "label": null,
          "row": 0,
          "powers": true
        },
        {
          "id": "gi8",
          "role": "poe",
          "label": null,
          "row": 0,
          "powers": true
        },
        {
          "id": "gi9",
          "role": "copper",
          "label": "no PoE",
          "row": 1,
          "powers": false
        },
        {
          "id": "gi10",
          "role": "copper",
          "label": "no PoE",
          "row": 1,
          "powers": false
        },
        {
          "id": "sfp11",
          "role": "sfp",
          "label": null,
          "row": 1,
          "powers": false
        },
        {
          "id": "sfp12",
          "role": "sfp",
          "label": null,
          "row": 1,
          "powers": false
        },
        {
          "id": "PWR1",
          "role": "power-in",
          "label": null,
          "row": 2,
          "powers": false
        },
        {
          "id": "PWR2",
          "role": "power-in",
          "label": null,
          "row": 2,
          "powers": false
        }
      ],
      "datasheet_url": "https://www.planet.com.tw/en/product/igs-4215-8up2t2s",
      "image": null,
      "notes": "8x PoE++ (gi1-gi8), 2x copper with no PoE (gi9-gi10), 2x SFP. 240 W budget, and only above that if BOTH DC inputs are wired. PoE has been left unmanaged since 2026-09-14 - the switch negotiates per port.",
      "aliases": [
        "IGS-4215-8UP2T2S",
        "IGS-4215"
      ]
    },
    "Teltonika RUTM08": {
      "model": "Teltonika RUTM08",
      "vendor": "Teltonika Networks",
      "kind": "router",
      "form_factor": "din-rail",
      "ports": null,
      "datasheet_url": "https://teltonika-networks.com/products/routers/rutm08",
      "image": null,
      "notes": "The site gateway and its only DHCP server.",
      "aliases": [
        "RUTM08"
      ]
    },
    "Teltonika TSW202": {
      "model": "Teltonika TSW202",
      "vendor": "Teltonika Networks",
      "kind": "switch",
      "form_factor": "din-rail",
      "ports": null,
      "datasheet_url": "https://teltonika-networks.com/products/switches/tsw202",
      "image": null,
      "notes": "Managed switch. Some units are the PROFINET variant, which ships with no address and cannot be found by the bench tool.",
      "aliases": [
        "TSW202"
      ]
    },
    "Teltonika OTD500": {
      "model": "Teltonika OTD500",
      "vendor": "Teltonika Networks",
      "kind": "modem",
      "form_factor": "outdoor",
      "ports": null,
      "datasheet_url": "https://teltonika-networks.com/products/modems/otd500",
      "image": null,
      "notes": "Outdoor unit; provides the WAN feed to the router.",
      "aliases": [
        "OTD500"
      ]
    },
    "AR-300": {
      "model": "AR-300",
      "vendor": "Magosys Systems",
      "kind": "radar",
      "form_factor": "outdoor",
      "ports": null,
      "datasheet_url": null,
      "image": null,
      "notes": "Draws roughly 35 W over PoE. Pinned by RF channel 0-3.",
      "aliases": [
        "Magos AR-300",
        "AR300"
      ]
    },
    "SR1000-I": {
      "model": "SR1000-I",
      "vendor": "Magosys Systems",
      "kind": "radar",
      "form_factor": "outdoor",
      "ports": null,
      "datasheet_url": null,
      "image": null,
      "notes": "The first Magos model here confirmed by reading a live unit's own API rather than inferred: two at kela-fob-03 on 2026-09-14, both on System Software 1.1.4 with Dashboard 2.4.3, DSP 1.2.4 and FPGA 1.2.6. Reports four independently-versioned components, so 'firmware' on a Magos radar is a set, not a string. Worth noting how it was found: the shortlist inferred from bench-central run records was AR-300 / SR1000-F / SR500-F, and the right answer was in none of them — the archive simply had no '-I' variant in it.",
      "aliases": [
        "Magos SR1000-I",
        "SR1000I"
      ]
    },
    "SR1000-F": {
      "model": "SR1000-F",
      "vendor": "Magosys Systems",
      "kind": "radar",
      "form_factor": "outdoor",
      "ports": null,
      "datasheet_url": null,
      "image": null,
      "notes": "Seen in bench-central run records alongside the AR-300.",
      "aliases": [
        "Magos SR1000-F"
      ]
    },
    "SR500-F": {
      "model": "SR500-F",
      "vendor": "Magosys Systems",
      "kind": "radar",
      "form_factor": "outdoor",
      "ports": null,
      "datasheet_url": null,
      "image": null,
      "notes": "Seen in bench-central run records alongside the AR-300.",
      "aliases": [
        "Magos SR500-F"
      ]
    },
    "AR Processing Unit (APU)": {
      "model": "AR Processing Unit (APU)",
      "vendor": "Nvidia",
      "kind": "apu",
      "form_factor": "box",
      "ports": null,
      "datasheet_url": null,
      "image": null,
      "notes": "Jetson-based, so its MAC resolves to NVIDIA, not to Magos. That is the cleanest way to tell an APU from a radar by MAC alone: across 65 bench-central runs the split is absolute - 21/21 APUs are NVIDIA prefixes, 44/44 radars are Magosys. Firmware floor 3.1.2.",
      "aliases": [
        "Magos APU",
        "APU"
      ]
    },
    "PC464A1": {
      "model": "PC464A1",
      "vendor": "HangZhou JuRu Technology",
      "kind": "camera",
      "form_factor": "outdoor",
      "ports": null,
      "datasheet_url": null,
      "image": null,
      "notes": "Thermal camera on the BC:74:D7 (HangZhou JuRu) prefix. In bench-central every camera on that prefix reports PC464A1. Typically on the PoE switch's gi9, which supplies NO power - it needs an external feed.",
      "aliases": [
        "Raythink PC464A1"
      ]
    },
    "XX-MVP-PC4-V100": {
      "model": "XX-MVP-PC4-V100",
      "vendor": "RayThink Technology",
      "kind": "camera",
      "form_factor": "outdoor",
      "ports": null,
      "datasheet_url": null,
      "image": null,
      "notes": "The newer camera, on the AC:86:D1 (RayThink Technology) prefix. A different unit from the PC464A1 despite both being 'the Raythink camera' in conversation.",
      "aliases": [
        "MVP-PC4"
      ]
    },
    "Provision-ISR PR-HS15W-IP": {
      "model": "Provision-ISR PR-HS15W-IP",
      "vendor": "Provision-ISR",
      "kind": "speaker",
      "form_factor": "outdoor",
      "ports": null,
      "datasheet_url": null,
      "image": null,
      "notes": "IP speaker, roughly 20 W over PoE. Arrives on DHCP at the bench.",
      "aliases": [
        "PR-HS15W-IP"
      ]
    }
  }
};
