#!/usr/bin/env python3
"""Summarise the bench-central archive into reference data for the dashboard.

This is what turns "unknown model" into "one of these three", so the page has
to be able to show the basis for a narrowing rather than asking anyone to
take it on faith. Read-only: GETs against the collector, nothing written.

    ./make_archive_context.py --central http://techops-automations-host:8100 \\
        -o ui/archive-data.js

Regenerate whenever the archive has grown; the numbers on the page are a
snapshot and the page says when it was taken.
"""
from __future__ import annotations

import argparse
import collections
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import bench_central
import oui

# Which tool configures which kind of device. Used only to label the summary.
TOOL_KINDS = {
    "magos-radar": "radar",
    "magos-apu": "apu",
    "rutm": "router",
    "otd": "modem",
    "tsw": "switch",
    "raythink": "camera",
    "speaker": "speaker",
    "planet": "poe-switch",
}


def build(client: bench_central.Client, table: dict, limit: int = 1000) -> dict:
    health = client.health()
    payload = client._get("/api/v1/runs", {"limit": limit})
    runs = payload.get("runs") or []

    models = collections.defaultdict(lambda: collections.defaultdict(set))
    vendors = collections.defaultdict(collections.Counter)
    firmwares = collections.defaultdict(set)
    no_mac = collections.Counter()

    for run in runs:
        tool = run.get("tool") or "(unknown tool)"
        mac = (run.get("mac") or "").strip()
        vendor = None
        try:
            found = oui.lookup(mac, table)
            if found and not found.is_registrar:
                vendor = found.name
        except oui.OuiError:
            no_mac[tool] += 1

        if vendor:
            vendors[tool][vendor] += 1
        if run.get("model"):
            models[tool][vendor or "(vendor unresolved)"].add(str(run["model"]))
        firmware = run.get("firmware")
        if firmware and str(firmware) != "unknown":
            firmwares[tool].add(str(firmware))

    try:
        sites = client._get("/api/v1/filters").get("sites") or []
    except bench_central.CentralError:
        sites = []

    return {
        "collector": client.base_url,
        "queried_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "runs_total": health.get("runs"),
        "device_labels": health.get("device_labels"),
        "runs_sampled": len(runs),
        "sites": sorted(sites),
        "by_tool": {
            tool: {
                "kind": TOOL_KINDS.get(tool, "unknown"),
                "models": {v: sorted(m) for v, m in sorted(models[tool].items())},
                "vendors": dict(vendors[tool].most_common()),
                "firmwares": sorted(firmwares[tool]),
                "runs_without_mac": no_mac.get(tool, 0),
            }
            for tool in sorted(set(models) | set(vendors) | set(firmwares))
        },
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--central", required=True)
    parser.add_argument("--db", help="path to nmap-mac-prefixes")
    parser.add_argument("--limit", type=int, default=1000)
    parser.add_argument("-o", "--out", help="write JS here instead of stdout")
    args = parser.parse_args(argv)

    try:
        table = oui.load_db(oui.find_db(args.db))
    except oui.OuiError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    client = bench_central.Client(args.central)
    try:
        context = build(client, table, args.limit)
    except bench_central.CentralError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    text = (
        "// Generated by make_archive_context.py - do not edit.\n"
        f"window.ARCHIVE_CONTEXT = {json.dumps(context, indent=2)};\n"
    )
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"wrote {args.out} ({context['runs_sampled']} runs sampled)",
              file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
